# Main application settings.
app:
  APP_NAME:     "sounder"
  APP_VERSION:  "0.0.1"
# Logging settings.
log:
  DEF_LEVEL:     20
  MAX_SIZE:      250000
  MAX_FILES:     3
# Sound capture and manipulation settings.
sound:
  SAMPLE_RATE:   44100
  SAMPLE_DUR:    5
  BURN_SECS:     0.5
  FFT_MIN_HZ:    25
  FFT_MAX_HZ:    1700
  FIG_X_SIZE:    12
  FIG_Y_SIZE:    5
  PLOT_X_TICKS:  15
  PLOT_TICK_RES: 10
  PLOT_1ST_OCT:  3
  PLOT_OCTAVES:  3
  FFT_AVG_WIN:   75
# Progress bar settings.
progress:
  PROG_WIDTH:    50
  BAR_WARNING:   35
