# Main application settings.
app:
  APP_NAME:     "sounder"
  APP_VERSION:  "0.0.1"
# Sound capture and manipulation settings.
sound:
  SAMPLE_RATE:    44100
  SAMPLE_DUR:     10
  BURN_SECS:      0.5
  FFT_MIN_HZ:     25
  FFT_MAX_HZ:     2500
  FIG_X_SIZE:     8
  FIG_Y_SIZE:     6
  PLOT_X_TICKS:   15
  PLOT_TICK_RES:  5
  FFT_AVG_WIN:    20
